# -*- coding: utf-8 -*-
"""unet-march20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUnnWHz3rjjeKN71Vth0mVQjWEK7DTNP
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Path to the folder containing test images
test_folder = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/'

# List all files in the folder
print(f"Files in {test_folder}:")
print(os.listdir(test_folder))

import json

# Load and read the JSON file
json_file_path = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/road_trainval_v1.0.json'

with open(json_file_path, 'r') as f:
    data = json.load(f)

# Print the first few entries to understand the structure
print(json.dumps(data, indent=4)[:1])  # Print first 10 characters for a quick look



import json
import numpy as np
import cv2
import os
from concurrent.futures import ThreadPoolExecutor

json_path = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/road_trainval_v1.0.json'

image_folder = '/content/drive/Shareddrives/Road_R_Dataset/ROAD-R-2023-Challenge-main/road/rgb-images/2015-03-03-11-31-36_stereo_centre_01/'

mask_dir = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/masks'
os.makedirs(mask_dir, exist_ok=True)

with open(json_path) as f:
    annotations = json.load(f)

img_cache = {}

def resize_image(img, target_height=256, target_width=256):
    return cv2.resize(img, (target_width, target_height))

def create_mask(image_name, annotations):
    if image_name not in img_cache:
        img_path = os.path.join(image_folder, image_name)
        img = cv2.imread(img_path)
       
        img_cache[image_name] = img
    else:
        img = img_cache[image_name]

    height, width = img.shape[:2]
    mask = np.zeros((height, width), dtype=np.uint8)

    for annotation in annotations.get(image_name, []):
        points = np.array(annotation['polygon'], dtype=np.int32)

        cv2.fillPoly(mask, [points], 255)

    return mask

def process_image(image_name):
    if image_name.endswith('.jpg') and image_name in annotations:
        mask = create_mask(image_name, annotations)
        mask_path = os.path.join(mask_dir, f"mask_{image_name}")
        cv2.imwrite(mask_path, mask)

with ThreadPoolExecutor() as executor:
    executor.map(process_image, os.listdir(image_folder))

print(f"Generated masks are saved in {mask_dir}")

import os

image_dir = '/content/drive/Shareddrives/Road_R_Dataset/ROAD-R-2023-Challenge-main/road/rgb-images/2015-03-03-11-31-36_stereo_centre_01/'
mask_dir = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/masks'

image_files = os.listdir(image_dir)
mask_files = os.listdir(mask_dir)

print("Total number of image files:", len(image_files))
print("Total number of mask files:", len(mask_files))

print("First few image filenames:", image_files[:5])
print("First few mask filenames:", mask_files[:5])

print("Total number of image files:", len(image_files))
print("Total number of mask files:", len(mask_files))

import os
from PIL import Image

images_dir = '/content/drive/Shareddrives/Road_R_Dataset/ROAD-R-2023-Challenge-main/road/rgb-images/2015-03-03-11-31-36_stereo_centre_01/'
masks_dir = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/masks'

image_files = sorted(os.listdir(images_dir))
mask_files = sorted(os.listdir(masks_dir))

if len(image_files) != len(mask_files):
    print("Warning: The number of images and masks do not match!")

for image_file, mask_file in zip(image_files, mask_files):
    image_path = os.path.join(images_dir, image_file)
    mask_path = os.path.join(masks_dir, mask_file)

    image = Image.open(image_path)
    mask = Image.open(mask_path)

    if image.size != mask.size:
        print(f"Dimension mismatch: {image_file} and {mask_file} have different sizes!")
    else:
        print(f"Verified: {image_file} and {mask_file} have matching dimensions.")

import os

image_folder = '/content/drive/Shareddrives/Road_R_Dataset/ROAD-R-2023-Challenge-main/road/rgb-images/2015-03-03-11-31-36_stereo_centre_01/'  # Change this path if needed
mask_folder = '/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/masks'  # Change this path if needed

image_files = [f for f in os.listdir(image_folder) if f.endswith('.jpg')]
mask_files = [f for f in os.listdir(mask_folder) if f.endswith('.jpg')]

mask_basename = [os.path.splitext(f)[0].replace('mask_', '') for f in mask_files]

image_basename = [os.path.splitext(f)[0] for f in image_files]

common_files = list(set(image_basename) & set(mask_basename))

selected_images = [img for img in image_files if os.path.splitext(img)[0] in common_files]
selected_masks = [mask for mask in mask_files if os.path.splitext(mask)[0].replace('mask_', '') in common_files]

print("Number of selected images:", len(selected_images))
print("Number of selected masks:", len(selected_masks))

print("Number of images:", len(images))
print("Number of masks:", len(masks))

import cv2
import numpy as np
from sklearn.model_selection import train_test_split

def resize_image(image, target_height=256, target_width=256):
    return cv2.resize(image, (target_width, target_height), interpolation=cv2.INTER_LINEAR)

resized_images = []
resized_masks = []

for image_file, mask_file in zip(selected_images, selected_masks):
    img = cv2.imread(os.path.join(image_folder, image_file))
    mask = cv2.imread(os.path.join(mask_folder, mask_file), cv2.IMREAD_GRAYSCALE)

    resized_img = resize_image(img)
    resized_mask = resize_image(mask)

    resized_images.append(resized_img)
    resized_masks.append(resized_mask)

resized_images = np.array(resized_images)
resized_masks = np.array(resized_masks)

resized_images = resized_images / 255.0
resized_masks = resized_masks / 255.0  # Assuming masks are binary (0 or 1)

X_train, X_val, y_train, y_val = train_test_split(resized_images, resized_masks, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape)
print("Validation set size:", X_val.shape)

print("Number of images:", len(images))
print("Number of masks:", len(masks))

import tensorflow as tf
from tensorflow.keras import layers, models

def unet_model(input_size=(256, 256, 3)):
    print("Defining U-Net model...")
    inputs = layers.Input(input_size)

    c1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
    c1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(c1)
    p1 = layers.MaxPooling2D((2, 2))(c1)

    c2 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(p1)
    c2 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(c2)
    p2 = layers.MaxPooling2D((2, 2))(c2)

    c3 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(p2)
    c3 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(c3)
    p3 = layers.MaxPooling2D((2, 2))(c3)

    c4 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(p3)
    c4 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(c4)
    p4 = layers.MaxPooling2D((2, 2))(c4)

    c5 = layers.Conv2D(1024, (3, 3), activation='relu', padding='same')(p4)
    c5 = layers.Conv2D(1024, (3, 3), activation='relu', padding='same')(c5)

    # Expansive Path (Decoder)
    u6 = layers.Conv2DTranspose(512, (3, 3), strides=(2, 2), padding='same')(c5)
    u6 = layers.concatenate([u6, c4])
    c6 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(u6)
    c6 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(c6)

    u7 = layers.Conv2DTranspose(256, (3, 3), strides=(2, 2), padding='same')(c6)
    u7 = layers.concatenate([u7, c3])
    c7 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(u7)
    c7 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(c7)

    u8 = layers.Conv2DTranspose(128, (3, 3), strides=(2, 2), padding='same')(c7)
    u8 = layers.concatenate([u8, c2])
    c8 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(u8)
    c8 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(c8)

    u9 = layers.Conv2DTranspose(64, (3, 3), strides=(2, 2), padding='same')(c8)
    u9 = layers.concatenate([u9, c1])
    c9 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(u9)
    c9 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(c9)

    outputs = layers.Conv2D(1, (1, 1), activation='sigmoid')(c9)

    model = models.Model(inputs, outputs)
    return model

print("Creating U-Net model...")
model = unet_model()

print("Compiling the model...")
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("Training the model...")
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=10,  
    batch_size=4  
)

print("Saving the model...")
model.save('/content/drive/My Drive/RGB_Dec20_Road-r-mydrive/unet_model.h5')

print("Model training and saving completed.")

import matplotlib.pyplot as plt

history_dict = history.history

# Plot training & validation accuracy values
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(history_dict['accuracy'], label='Training Accuracy')
plt.plot(history_dict['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_dict['loss'], label='Training Loss')
plt.plot(history_dict['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()



